export const ADDED = 'todos/added'
export const TOGGLED = 'todos/toggled'
export const COLOR_SELECTED = 'todos/color_selected'
export const DELETED = 'todos/deleted'
export const ALL_COMPLETED = 'todos/all_completed'
export const CLEAR_COMPLETED = 'todos/clear_completed'
