export const ADDED = 'todos/added'
export const TOGGLED = 'todos/toggled'
export const COLOR_SELECTED = 'todos/color_selected'
export const DELETED = 'todos/deleted'
export const ALL_COMPLITED = 'todos/all_complited'
export const CLEAR_COMPLITED = 'todos/clear_complited'
